version: '2'
services:
  prometheus:
    image: "jotak/falco-prometheus:latest"
    ports:
      - "9090:9090"
  grafana:
    image: "jotak/falco-grafana:latest"
    ports:
      - "3000:3000"
  falco:
    image: "jotak/falco-the-hawk:latest"
    ports:
      - "8081:8081"
