apiVersion: v1
kind: Template
metadata:
  name: falcOS
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: grafana
    name: grafana
  spec:
    replicas: 1
    selector:
      app: grafana
      deploymentconfig: grafana
    template:
      metadata:
        labels:
          app: grafana
          deploymentconfig: grafana
      spec:
        containers:
        - image: hawkular/hawkular-grafana-datasource:resolve-vars-annots
          imagePullPolicy: Always
          name: grafana
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: grafana
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: bootstrap
    name: bootstrap
  spec:
    replicas: 1
    selector:
      app: bootstrap
      deploymentconfig: bootstrap
    template:
      metadata:
        labels:
          app: bootstrap
          deploymentconfig: bootstrap
      spec:
        containers:
        - env:
          - name: TENANT
            value: falco
          - name: DASHBOARDS
            value: vertx-hwk falco
          - name: HAWKULAR_URI
            value: "https://metrics-openshift-infra.192.168.1.29.xip.io/hawkular/metrics"
          - name: HAWKULAR_AUTH_TOKEN
            value: "dsdsdsdsdsdsd"
          image: jotak/hawkular-grafana-bootstrap:latest
          imagePullPolicy: Always
          name: bootstrap
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: falco
    name: falco
  spec:
    replicas: 1
    selector:
      app: falco
      deploymentconfig: falco
    template:
      metadata:
        labels:
          app: falco
          deploymentconfig: falco
      spec:
        containers:
        - env:
          - name: HAWKULAR_HOST
            value: "metrics-openshift-infra.192.168.1.29.xip.io"
          - name: HAWKULAR_PORT
            value: "443"
          - name: HAWKULAR_HTTPS
            value: "true"
          - name: HAWKULAR_TENANT
            value: falco
          - name: HAWKULAR_AUTH_TOKEN
            value: "dsdsdsdsdsdsd"
          image: jotak/falco-the-hawk:latest
          imagePullPolicy: Always
          name: falco
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: falco
    name: falco
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: falco
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: falco
  spec:
    to:
      kind: Service
      name: falco
- apiVersion: v1
  kind: Route
  metadata:
    name: grafana
  spec:
    to:
      kind: Service
      name: grafana
- apiVersion: v1
  kind: Route
  metadata:
    name: hawkular
  spec:
    to:
      kind: Service
      name: hawkular
